name: CI

on:
  push:
  pull_request:

jobs:
  rust-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@1.93.1
        with:
          components: rustfmt, clippy

      - name: DSAPI check
        run: ./scripts/dsapi.sh check

  c-example-build:
    runs-on: ubuntu-24.04
    needs: rust-check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@1.93.1

      - name: Build C example
        run: ./scripts/build_c_example.sh
